services:
  upturtle:
    image: ghcr.io/z3nto/upturtle:main
    container_name: upturtle
    ports:
      - "8080:8080"
    user: 1001:10001 # only if you use bind mounts
    environment:
      LISTEN_ADDR: ":8080"
      #UPTURTLE_CONFIG_PATH: "/data/conf/config.json"
    volumes:
      - upturtle:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # only if you want to monitor docker containers
    restart: unless-stopped

volumes:
  upturtle_conf:  # Persistent storage for configuration
  upturtle_data:  # Persistent storage for SQLite database
