services:
  upturtle:
    build: .
    container_name: upturtle
    ports:
      - "8080:8080"
    environment:
      LISTEN_ADDR: ":8080"
      UPTURTLE_CONFIG_PATH: "/conf/config.json"
    volumes:
      - upturtle_conf:/conf
      - upturtle_data:/data  # For SQLite database storage
    restart: unless-stopped

volumes:
  upturtle_conf:  # Persistent storage for configuration
  upturtle_data:  # Persistent storage for SQLite database
